<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/employee/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.employee.'), function () {

Route::get('employees', ['as'=> 'employees.index', 'uses' => 'Employee\EmployeeController@index']);
Route::post('employees', ['as'=> 'employees.store', 'uses' => 'Employee\EmployeeController@store']);
Route::get('employees/create', ['as'=> 'employees.create', 'uses' => 'Employee\EmployeeController@create']);
Route::put('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'Employee\EmployeeController@update']);
Route::patch('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'Employee\EmployeeController@update']);
Route::get('employees/{id}/delete', ['as' => 'employees.delete', 'uses' => 'Employee\EmployeeController@getDelete']);
Route::get('employees/{id}/confirm-delete', ['as' => 'employees.confirm-delete', 'uses' => 'Employee\EmployeeController@getModalDelete']);
Route::get('employees/{employees}', ['as'=> 'employees.show', 'uses' => 'Employee\EmployeeController@show']);
Route::get('employees/{employees}/edit', ['as'=> 'employees.edit', 'uses' => 'Employee\EmployeeController@edit']);

});


Route::group(array('prefix' => 'admin/document/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.document.'), function () {

Route::get('documents', ['as'=> 'documents.index', 'uses' => 'Document\DocumentController@index']);
Route::post('documents', ['as'=> 'documents.store', 'uses' => 'Document\DocumentController@store']);
Route::get('documents/create', ['as'=> 'documents.create', 'uses' => 'Document\DocumentController@create']);
Route::put('documents/{documents}', ['as'=> 'documents.update', 'uses' => 'Document\DocumentController@update']);
Route::patch('documents/{documents}', ['as'=> 'documents.update', 'uses' => 'Document\DocumentController@update']);
Route::get('documents/{id}/delete', ['as' => 'documents.delete', 'uses' => 'Document\DocumentController@getDelete']);
Route::get('documents/{id}/confirm-delete', ['as' => 'documents.confirm-delete', 'uses' => 'Document\DocumentController@getModalDelete']);
Route::get('documents/{documents}', ['as'=> 'documents.show', 'uses' => 'Document\DocumentController@show']);
Route::get('documents/{documents}/edit', ['as'=> 'documents.edit', 'uses' => 'Document\DocumentController@edit']);

});


Route::group(array('prefix' => 'admin/search/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.search.'), function () {

Route::get('searches', ['as'=> 'searches.index', 'uses' => 'Search\SearchController@index']);
Route::post('searches', ['as'=> 'searches.store', 'uses' => 'Search\SearchController@store']);
Route::get('searches/create', ['as'=> 'searches.create', 'uses' => 'Search\SearchController@create']);
Route::put('searches/{searches}', ['as'=> 'searches.update', 'uses' => 'Search\SearchController@update']);
Route::patch('searches/{searches}', ['as'=> 'searches.update', 'uses' => 'Search\SearchController@update']);
Route::get('searches/{id}/delete', ['as' => 'searches.delete', 'uses' => 'Search\SearchController@getDelete']);
Route::get('searches/{id}/confirm-delete', ['as' => 'searches.confirm-delete', 'uses' => 'Search\SearchController@getModalDelete']);
Route::get('searches/{searches}', ['as'=> 'searches.show', 'uses' => 'Search\SearchController@show']);
Route::get('searches/{searches}/edit', ['as'=> 'searches.edit', 'uses' => 'Search\SearchController@edit']);

});
