<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/employee/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.employee.'), function () {

Route::get('employees', ['as'=> 'employees.index', 'uses' => 'Employee\EmployeeController@index']);
Route::post('employees', ['as'=> 'employees.store', 'uses' => 'Employee\EmployeeController@store']);
Route::get('employees/create', ['as'=> 'employees.create', 'uses' => 'Employee\EmployeeController@create']);
Route::put('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'Employee\EmployeeController@update']);
Route::patch('employees/{employees}', ['as'=> 'employees.update', 'uses' => 'Employee\EmployeeController@update']);
Route::get('employees/{id}/delete', ['as' => 'employees.delete', 'uses' => 'Employee\EmployeeController@getDelete']);
Route::get('employees/{id}/confirm-delete', ['as' => 'employees.confirm-delete', 'uses' => 'Employee\EmployeeController@getModalDelete']);
Route::get('employees/{employees}', ['as'=> 'employees.show', 'uses' => 'Employee\EmployeeController@show']);
Route::get('employees/{employees}/edit', ['as'=> 'employees.edit', 'uses' => 'Employee\EmployeeController@edit']);

});


Route::group(array('prefix' => 'admin/document/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.document.'), function () {

Route::get('documents', ['as'=> 'documents.index', 'uses' => 'Document\DocumentController@index']);
Route::post('documents', ['as'=> 'documents.store', 'uses' => 'Document\DocumentController@store']);
Route::get('documents/create', ['as'=> 'documents.create', 'uses' => 'Document\DocumentController@create']);
Route::put('documents/{documents}', ['as'=> 'documents.update', 'uses' => 'Document\DocumentController@update']);
Route::patch('documents/{documents}', ['as'=> 'documents.update', 'uses' => 'Document\DocumentController@update']);
Route::get('documents/{id}/delete', ['as' => 'documents.delete', 'uses' => 'Document\DocumentController@getDelete']);
Route::get('documents/{id}/confirm-delete', ['as' => 'documents.confirm-delete', 'uses' => 'Document\DocumentController@getModalDelete']);
Route::get('documents/{documents}', ['as'=> 'documents.show', 'uses' => 'Document\DocumentController@show']);
Route::get('documents/{documents}/edit', ['as'=> 'documents.edit', 'uses' => 'Document\DocumentController@edit']);

});


Route::group(array('prefix' => 'admin/search/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.search.'), function () {

Route::get('searches', ['as'=> 'searches.index', 'uses' => 'Search\SearchController@index']);
// Route::post('searches', ['as'=> 'searches.store', 'uses' => 'Search\SearchController@store']);
// Route::get('searches/create', ['as'=> 'searches.create', 'uses' => 'Search\SearchController@create']);
// Route::put('searches/{searches}', ['as'=> 'searches.update', 'uses' => 'Search\SearchController@update']);
// Route::patch('searches/{searches}', ['as'=> 'searches.update', 'uses' => 'Search\SearchController@update']);
// Route::get('searches/{id}/delete', ['as' => 'searches.delete', 'uses' => 'Search\SearchController@getDelete']);
// Route::get('searches/{id}/confirm-delete', ['as' => 'searches.confirm-delete', 'uses' => 'Search\SearchController@getModalDelete']);
// Route::get('searches/{searches}', ['as'=> 'searches.show', 'uses' => 'Search\SearchController@show']);
// Route::get('searches/{searches}/edit', ['as'=> 'searches.edit', 'uses' => 'Search\SearchController@edit']);

//    # custom datatables

Route::get('searches/sliderData', 'Search\SearchController@sliderData')->name('SearchController.sliderData');
Route::get('searches/radioData', 'Search\SearchController@radioData')->name('SearchController.radioData');
Route::get('searches/selectData', 'Search\SearchController@selectData')->name('SearchController.selectData');
Route::get('searches/buttonData', 'Search\SearchController@buttonData')->name('SearchController.buttonData');
Route::get('searches/totalData', 'Search\SearchController@totalData')->name('SearchController.totalData');


});
 

Route::group(array('prefix' => 'admin/documnt/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.documnt.'), function () {

Route::get('documnts', ['as'=> 'documnts.index', 'uses' => 'Documnt\DocumntController@index']);
Route::post('documnts', ['as'=> 'documnts.store', 'uses' => 'Documnt\DocumntController@store']);
Route::get('documnts/create', ['as'=> 'documnts.create', 'uses' => 'Documnt\DocumntController@create']);
Route::put('documnts/{documnts}', ['as'=> 'documnts.update', 'uses' => 'Documnt\DocumntController@update']);
Route::patch('documnts/{documnts}', ['as'=> 'documnts.update', 'uses' => 'Documnt\DocumntController@update']);
Route::get('documnts/{id}/delete', ['as' => 'documnts.delete', 'uses' => 'Documnt\DocumntController@getDelete']);
Route::get('documnts/{id}/confirm-delete', ['as' => 'documnts.confirm-delete', 'uses' => 'Documnt\DocumntController@getModalDelete']);
Route::get('documnts/{documnts}', ['as'=> 'documnts.show', 'uses' => 'Documnt\DocumntController@show']);
Route::get('documnts/{documnts}/edit', ['as'=> 'documnts.edit', 'uses' => 'Documnt\DocumntController@edit']);

});


Route::group(array('prefix' => 'admin/documnt/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.documnt.'), function () {

Route::get('documnts', ['as'=> 'documnts.index', 'uses' => 'Documnt\DocumntController@index']);
Route::post('documnts', ['as'=> 'documnts.store', 'uses' => 'Documnt\DocumntController@store']);
Route::get('documnts/create', ['as'=> 'documnts.create', 'uses' => 'Documnt\DocumntController@create']);
Route::put('documnts/{documnts}', ['as'=> 'documnts.update', 'uses' => 'Documnt\DocumntController@update']);
Route::patch('documnts/{documnts}', ['as'=> 'documnts.update', 'uses' => 'Documnt\DocumntController@update']);
Route::get('documnts/{id}/delete', ['as' => 'documnts.delete', 'uses' => 'Documnt\DocumntController@getDelete']);
Route::get('documnts/{id}/confirm-delete', ['as' => 'documnts.confirm-delete', 'uses' => 'Documnt\DocumntController@getModalDelete']);
Route::get('documnts/{documnts}', ['as'=> 'documnts.show', 'uses' => 'Documnt\DocumntController@show']);
Route::get('documnts/{documnts}/edit', ['as'=> 'documnts.edit', 'uses' => 'Documnt\DocumntController@edit']);

});
